// <auto-generated />
using System;
using LuminKazan.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LuminKazan.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LuminKazan.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Comment")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StudioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId");

                    b.HasIndex("StudioId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("LuminKazan.Models.ContactMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("ContactMessages");
                });

            modelBuilder.Entity("LuminKazan.Models.Photographer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Biography")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ExperienceYears")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("InstagramLink")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("ProfileImagePath")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Specialization")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("TelegramLink")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Photographers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Biography = "Профессиональный фотограф из Казани, работающий в жанрах индивидуальной, семейной, fashion и контент-съемки. Основной акцент - на эстетике, свете и живой эмоциональной подаче.",
                            Email = "",
                            ExperienceYears = 5,
                            FullName = "Алина Валеева",
                            InstagramLink = "",
                            Phone = "",
                            ProfileImagePath = "",
                            Specialization = "Современный художественный и коммерческий фотограф",
                            TelegramLink = ""
                        });
                });

            modelBuilder.Entity("LuminKazan.Models.PortfolioCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("PortfolioCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "",
                            Name = "Индивидуальная съемка"
                        },
                        new
                        {
                            Id = 2,
                            Description = "",
                            Name = "Семейная съемка"
                        },
                        new
                        {
                            Id = 3,
                            Description = "",
                            Name = "Love Story"
                        },
                        new
                        {
                            Id = 4,
                            Description = "",
                            Name = "Fashion"
                        },
                        new
                        {
                            Id = 5,
                            Description = "",
                            Name = "Контент-съемка"
                        },
                        new
                        {
                            Id = 6,
                            Description = "",
                            Name = "Студийная съемка"
                        });
                });

            modelBuilder.Entity("LuminKazan.Models.PortfolioImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Caption")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("PortfolioItemId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PortfolioItemId");

                    b.ToTable("PortfolioImages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Caption = "Портрет в естественном свете",
                            ImagePath = "/images/portfolio/minimal-1.jpg",
                            PortfolioItemId = 1,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            Caption = "Минималистичный кадр",
                            ImagePath = "/images/portfolio/minimal-2.jpg",
                            PortfolioItemId = 1,
                            SortOrder = 2
                        });
                });

            modelBuilder.Entity("LuminKazan.Models.PortfolioItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(1500)
                        .HasColumnType("nvarchar(1500)");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<int>("PhotographerId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ShootingDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("StudioId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("PhotographerId");

                    b.HasIndex("StudioId");

                    b.ToTable("PortfolioItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 6,
                            Description = "Студийная съемка в минималистичном интерьере с акцентом на форму и свет.",
                            ImagePath = "/images/portfolio/portfolio6.jpg",
                            IsFeatured = true,
                            PhotographerId = 1,
                            ShootingDate = new DateTime(2026, 3, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StudioId = 1,
                            Title = "Minimal Studio"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 3,
                            Description = "Эмоциональная love story съемка с теплой цветокоррекцией.",
                            ImagePath = "/images/portfolio/portfolio2.jpg",
                            IsFeatured = true,
                            PhotographerId = 1,
                            ShootingDate = new DateTime(2026, 1, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StudioId = 2,
                            Title = "Городская история"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Description = "Индивидуальная студийная съемка в мягком естественном свете.",
                            ImagePath = "/images/portfolio/portfolio3.jpg",
                            IsFeatured = true,
                            PhotographerId = 1,
                            ShootingDate = new DateTime(2025, 12, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StudioId = 1,
                            Title = "Светлый портрет"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Description = "Теплая семейная съемка в спокойной атмосфере.",
                            ImagePath = "/images/portfolio/portfolio4.jpg",
                            IsFeatured = true,
                            PhotographerId = 1,
                            ShootingDate = new DateTime(2025, 11, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StudioId = 3,
                            Title = "Семейное утро"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 5,
                            Description = "Съемка визуального контента для экспертного профиля и социальных сетей.",
                            ImagePath = "/images/portfolio/portfolio5.jpg",
                            IsFeatured = false,
                            PhotographerId = 1,
                            ShootingDate = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StudioId = 2,
                            Title = "Контент для бренда"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 4,
                            Description = "Стилизованная fashion-съемка для персонального бренда.",
                            ImagePath = "/images/portfolio/portfolio1.jpg",
                            IsFeatured = false,
                            PhotographerId = 1,
                            ShootingDate = new DateTime(2026, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StudioId = 4,
                            Title = "Fashion Frame"
                        });
                });

            modelBuilder.Entity("LuminKazan.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(1200)
                        .HasColumnType("nvarchar(1200)");

                    b.HasKey("Id");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClientName = "Анна",
                            CreatedAt = new DateTime(2026, 3, 12, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPublished = true,
                            Rating = 5,
                            Text = "Съемка прошла спокойно и профессионально. Получились живые фотографии, которые действительно похожи на меня."
                        },
                        new
                        {
                            Id = 2,
                            ClientName = "Мария",
                            CreatedAt = new DateTime(2026, 3, 18, 15, 30, 0, 0, DateTimeKind.Unspecified),
                            IsPublished = true,
                            Rating = 5,
                            Text = "Понравилось, что фотограф помогла с позированием и выбором студии. Результат получился очень аккуратным."
                        },
                        new
                        {
                            Id = 3,
                            ClientName = "Екатерина",
                            CreatedAt = new DateTime(2026, 4, 2, 10, 20, 0, 0, DateTimeKind.Unspecified),
                            IsPublished = true,
                            Rating = 5,
                            Text = "Заказывала съемку для личного бренда. Фотографии подошли и для сайта, и для социальных сетей."
                        });
                });

            modelBuilder.Entity("LuminKazan.Models.ScheduleBlock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Reason")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("StartAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("StartAt", "EndAt", "IsActive");

                    b.ToTable("ScheduleBlocks");
                });

            modelBuilder.Entity("LuminKazan.Models.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AllPhotosCount")
                        .HasColumnType("int");

                    b.Property<int>("DeliveryDays")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<bool>("IncludesStudio")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RetouchedPhotosCount")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AllPhotosCount = 40,
                            DeliveryDays = 5,
                            Description = "Короткая фотосессия для обновления контента или личных фото.",
                            DurationMinutes = 30,
                            IncludesStudio = true,
                            IsActive = true,
                            Price = 3500m,
                            RetouchedPhotosCount = 10,
                            Title = "Мини-съемка"
                        },
                        new
                        {
                            Id = 2,
                            AllPhotosCount = 80,
                            DeliveryDays = 7,
                            Description = "Полноценная персональная фотосессия с проработкой образа и локации.",
                            DurationMinutes = 60,
                            IncludesStudio = false,
                            IsActive = true,
                            Price = 7000m,
                            RetouchedPhotosCount = 20,
                            Title = "Индивидуальная съемка"
                        },
                        new
                        {
                            Id = 3,
                            AllPhotosCount = 100,
                            DeliveryDays = 7,
                            Description = "Эмоциональная и эстетичная фотосессия для пары.",
                            DurationMinutes = 90,
                            IncludesStudio = false,
                            IsActive = true,
                            Price = 9500m,
                            RetouchedPhotosCount = 25,
                            Title = "Love Story"
                        },
                        new
                        {
                            Id = 4,
                            AllPhotosCount = 100,
                            DeliveryDays = 7,
                            Description = "Фотосессия для семьи в студии или на выездной локации.",
                            DurationMinutes = 90,
                            IncludesStudio = false,
                            IsActive = true,
                            Price = 9000m,
                            RetouchedPhotosCount = 25,
                            Title = "Семейная съемка"
                        },
                        new
                        {
                            Id = 5,
                            AllPhotosCount = 150,
                            DeliveryDays = 10,
                            Description = "Создание фото-контента для бизнеса, блогеров и экспертов.",
                            DurationMinutes = 120,
                            IncludesStudio = false,
                            IsActive = true,
                            Price = 12000m,
                            RetouchedPhotosCount = 30,
                            Title = "Контент-съемка для бренда"
                        },
                        new
                        {
                            Id = 6,
                            AllPhotosCount = 50,
                            DeliveryDays = 3,
                            Description = "Съемка для резюме, сайта, социальных сетей, личного бренда и профессионального профиля.",
                            DurationMinutes = 60,
                            IncludesStudio = false,
                            IsActive = true,
                            Price = 4500m,
                            RetouchedPhotosCount = 15,
                            Title = "Бизнес-портрет"
                        });
                });

            modelBuilder.Entity("LuminKazan.Models.Studio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Description")
                        .HasMaxLength(1500)
                        .HasColumnType("nvarchar(1500)");

                    b.Property<string>("District")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("HallCount")
                        .HasColumnType("int");

                    b.Property<bool>("HasNaturalLight")
                        .HasColumnType("bit");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("InteriorStyle")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("PricePerHour")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("WebsiteUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Studios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Казань, ул. Баумана, 15",
                            Description = "Светлая минималистичная студия с большими окнами и мягким естественным светом.",
                            District = "Вахитовский",
                            HallCount = 2,
                            HasNaturalLight = true,
                            ImagePath = "",
                            InteriorStyle = "Минимализм",
                            IsActive = true,
                            Name = "White Hall Studio",
                            PricePerHour = 1800m,
                            WebsiteUrl = ""
                        },
                        new
                        {
                            Id = 2,
                            Address = "Казань, ул. Габдуллы Тукая, 84",
                            Description = "Интерьерная фотостудия в центре Казани с несколькими залами для портретных, семейных и коммерческих съемок.",
                            District = "Вахитовский",
                            HallCount = 4,
                            HasNaturalLight = true,
                            ImagePath = "",
                            InteriorStyle = "Классика, минимализм, интерьерные залы",
                            IsActive = true,
                            Name = "Studio1884",
                            PricePerHour = 2200m,
                            WebsiteUrl = ""
                        },
                        new
                        {
                            Id = 3,
                            Address = "Казань, ул. Вишневского, 2А лит К",
                            Description = "Фотостудия для портретных, семейных и контент-съемок с интерьерными зонами и удобным расположением в центральной части города.",
                            District = "Вахитовский",
                            HallCount = 2,
                            HasNaturalLight = true,
                            ImagePath = "",
                            InteriorStyle = "Светлый интерьер",
                            IsActive = true,
                            Name = "SEVER",
                            PricePerHour = 1600m,
                            WebsiteUrl = ""
                        },
                        new
                        {
                            Id = 4,
                            Address = "Казань, ул. Меховщиков, 80 к2",
                            Description = "Пространство для контент-съемок, портретов и коммерческих кадров с несколькими фотозонами.",
                            District = "Вахитовский",
                            HallCount = 4,
                            HasNaturalLight = false,
                            ImagePath = "",
                            InteriorStyle = "Современный интерьер",
                            IsActive = true,
                            Name = "Photobaza",
                            PricePerHour = 2500m,
                            WebsiteUrl = ""
                        },
                        new
                        {
                            Id = 5,
                            Address = "Казань, ул. Васильченко, 1 к153А, 4 этаж",
                            Description = "Пространство для портретных, fashion и коммерческих съемок с современными залами и возможностью работы с естественным и студийным светом.",
                            District = "Московский",
                            HallCount = 2,
                            HasNaturalLight = true,
                            ImagePath = "",
                            InteriorStyle = "Циклорама, современный интерьер, коммерческая съемка",
                            IsActive = true,
                            Name = "Delight Studio",
                            PricePerHour = 1700m,
                            WebsiteUrl = ""
                        },
                        new
                        {
                            Id = 6,
                            Address = "Казань, ул. Воскресенская, 20А",
                            Description = "Фотостудия для портретных, семейных и контент-съемок. Подходит для лаконичных кадров, съемок для личного бренда и небольших коммерческих проектов.",
                            District = "Кировский",
                            HallCount = 2,
                            HasNaturalLight = true,
                            ImagePath = "",
                            InteriorStyle = "Современный интерьер",
                            IsActive = true,
                            Name = "2Click",
                            PricePerHour = 1200m,
                            WebsiteUrl = ""
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("LuminKazan.Models.Booking", b =>
                {
                    b.HasOne("LuminKazan.Models.Service", "Service")
                        .WithMany("Bookings")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LuminKazan.Models.Studio", "Studio")
                        .WithMany("Bookings")
                        .HasForeignKey("StudioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Service");

                    b.Navigation("Studio");
                });

            modelBuilder.Entity("LuminKazan.Models.PortfolioImage", b =>
                {
                    b.HasOne("LuminKazan.Models.PortfolioItem", "PortfolioItem")
                        .WithMany("Images")
                        .HasForeignKey("PortfolioItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PortfolioItem");
                });

            modelBuilder.Entity("LuminKazan.Models.PortfolioItem", b =>
                {
                    b.HasOne("LuminKazan.Models.PortfolioCategory", "Category")
                        .WithMany("PortfolioItems")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LuminKazan.Models.Photographer", "Photographer")
                        .WithMany("PortfolioItems")
                        .HasForeignKey("PhotographerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LuminKazan.Models.Studio", "Studio")
                        .WithMany("PortfolioItems")
                        .HasForeignKey("StudioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");

                    b.Navigation("Photographer");

                    b.Navigation("Studio");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LuminKazan.Models.Photographer", b =>
                {
                    b.Navigation("PortfolioItems");
                });

            modelBuilder.Entity("LuminKazan.Models.PortfolioCategory", b =>
                {
                    b.Navigation("PortfolioItems");
                });

            modelBuilder.Entity("LuminKazan.Models.PortfolioItem", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("LuminKazan.Models.Service", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("LuminKazan.Models.Studio", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("PortfolioItems");
                });
#pragma warning restore 612, 618
        }
    }
}
